// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef PROYECTO1_H
#define PROYECTO1_H

#include <ngrest/common/Service.h>

#include <string>
#include <list>
#include "lista.h"

/*
    Este struct es una serializacion del struct 'estudiante' del archivo 'nodo.h',
    los cuales son equivalentes, ya que no se envian, ni reciben las estructuras
    como tal, sino un JSON
*/
struct estudianteSerial{
  int carnet;
  std::string dpi;
  std::string nombres;
  std::string apellidos;
  std::string nacimiento;
  std::string direccion;
  int creditos;
  std::string contrasena;
};

//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: proyecto1
class proyecto1: public ngrest::Service
{
public:
    // Here is an example of service operation
    //! Dummy description for the operation
    /*! Some detailed description of the operation */
    // To invoke this operation from browser open: http://localhost:9098/proyecto1/World!
    //
    // '*location' metacomment sets path to operation relative to service operation.
    // Default value is operation name.
    // This will bind "echo" method to resource path: http://host:port/proyecto1/{text}
    // *location: /{text}
    //
    // '*method' metacomment sets HTTP method for the operation. GET is default method.
    // *method: GET
    //
    std::string echo(const std::string& text);
    
    
    // *method: POST
    // */location: /insertarEstudiante/{estudiante}
    std::string insertarEstudiante(estudianteSerial estudiante);

    // *method: GET
    // */location: /getEstudiantes
    std::list<estudianteSerial> getEstudiantes();
};


#endif // PROYECTO1_H



